create table if not exists products(id serial primary key,
                name text not null,
                x double precision not null,
                y double precision not null,
                creationDate TIMESTAMPTZ not null,
                price float4 not null check (price > 0),
                partNumber text null check (length(partNumber) between 23 and 51 or partNumber = null),
                manufactureCost double precision null check (manufactureCost >= 0),
                unitOfMeasure varchar(20) not null check (unitOfMeasure IN ('METERS', 'CENTIMETERS', 'PCS', 'LITERS', 'MILLIGRAMS')),
                personName text,
                personHeight float4,
                eyeColor varchar(20) not null check (eyeColor IN ('GREEN', 'YELLOW', 'ORANGE', 'BROWN')),
                nationality varchar(20) null check (nationality in ('RUSSIA', 'GERMANY', 'FRANCE', 'SOUTH_KOREA', 'JAPAN', null)),
                userId serial references users(id));