create table if not exists products(id serial primary key,
                name text not null,
                x double precision not null,
                y double precision not null,
                creation_date TIMESTAMPTZ not null,
                price float4 not null check (price > 0),
                part_number text null check (length(part_number) between 23 and 51 or part_number = null),
                manufacture_cost double precision null check (manufacture_cost >= 0),
                unit_of_measure varchar(20) not null check (unit_of_measure IN ('METERS', 'CENTIMETERS', 'PCS', 'LITERS', 'MILLIGRAMS')),
                person_name text,
                person_height float4,
                person_eye_color varchar(20) not null check (person_eye_color IN ('GREEN', 'YELLOW', 'ORANGE', 'BROWN')),
                nationality varchar(20) null check (nationality in ('RUSSIA', 'GERMANY', 'FRANCE', 'SOUTH_KOREA', 'JAPAN', null)),
                user_id serial references users(id));